[package]
name = "kled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
minimax = { path = "../minimax" }
newcular = { path = "../newcular" }
# board-em-api = "0.1.0"